spring.application.name=job-portal-company-service

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportalcompanydb
spring.datasource.username=postgres
spring.datasource.password=manojkasu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.datasource-platform=org.hibernate.dialect.PostgreSQLDialect
