spring.application.name=job-portal-user-service

spring.datasource.driver-class-name =org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportaldb
spring.datasource.username=postgres
spring.datasource.password=MANOJKASU

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true