spring.application.name=job-portal-resume-service

server.port = 8083

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportalresumedb
spring.datasource.username=postgres
spring.datasource.password=MANOJKASU
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate-ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
