package com.manoj.job.domain;

public enum IndustryType {
    TECHNOLOGY,
    FINANCE_BANKING,
    HEALTHCARE,
    EDUCATION,
    MANUFACTURING,
    RETAIL_ECOMMERCE,
    HOSPITALITY_TOURISM,
    REAL_ESTATE,
    MEDIA_ENTERTAINMENTS,
    TRANSPORTATION_UTILITIES,
    ENERGY_UTILITIES,
    AGRICULTURE,
    CONSULTING,
    LEGAL,
    TELECOMMUNICATION,
    AUTOMATIVE,
    PHARMACEUTICAL,
    CONSTRUCTION,
    HUMAN_RESOURCES,
    MARKETING_ADVERTISERS,
    OTHER

}
